apiVersion: v1
kind: Pod
metadata:
  labels:
    run: frontend
  name: frontend
spec:
  containers:
    - name: frontend
      image: ruauka/frontend:latest
      env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"
        - name: CURRENCY_SERVICE_ADDR
          value: "currencyservice:7000"
        - name: CART_SERVICE_ADDR
          value: "cartservice:7070"
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "recommendationservice:8080"
        - name: SHIPPING_SERVICE_ADDR
          value: "shippingservice:50051"
        - name: CHECKOUT_SERVICE_ADDR
          value: "checkoutservice:5050"
        - name: AD_SERVICE_ADDR
          value: "adservice:9555"
        # # ENV_PLATFORM: One of: local, gcp, aws, azure, onprem, alibaba
        # # When not set, defaults to "local" unless running in GKE, otherwies auto-sets to gcp
        # - name: ENV_PLATFORM
        #   value: "aws"
        - name: ENABLE_PROFILER
          value: "0"
        # - name: CYMBAL_BRANDING
        #   value: "true"
        # - name: FRONTEND_MESSAGE
        #   value: "Replace this with a message you want to display on all pages."
